export const OPERATORS = {
  EQUAL: '$eq',
  NOT_EQUAL: '$ne',
  GREATER_THAN: '$gt',
  GREATER_OR_EQUAL: '$gte',
  LESS_THAN: '$lt',
  LESS_OR_EQUAL: '$lte',
  IN: '$in',
  NOT_IN: '$nin'
};

export const LOGICAL_OPERATORS = {
  AND: '$and',
  // NOT: '$not',
  OR: '$or'
};

export const FILTER_GROUPS = {
  USER_ATTRIBUTES: 'USER_ATTRIBUTES',
  LOCATION: 'LOCATION',
  USER_ACTIVIY_ATTRIBUTES: 'USER_ACTIVIY_ATTRIBUTES',
  DEVICE_AND_APP: 'DEVICE_AND_APP'
};

export const FILTERS = {
  EMAIL: 'email',
  GENDER: 'gender',
  NAME: 'name',
  LANGUAGE: 'language',
  PHONE: 'phone',
  LOCATION_LAT: 'location.lat',
  LOCATION_LNG: 'location.lng',
  COUNTRY: 'country',
  ADDRESS: 'address',
  STATE: 'state',
  CITY: 'city',
  ZIPCODE: 'zipcode',
  ACTIVITY: 'created',
  OS_NUMBER: 'osNumber',
  DEVICE_VENDOR: 'deviceVendor',
  DEVICE_MODEL: 'deviceModel',
  DEVICE_PLATFORM: 'devicePlatform',
  CARRIER: 'carrier',
  CONNECTIVITY_TYPE: 'connectivityType',
  SDK_VERSION: 'sdkVersion',
  PACKAGE_NAME: 'packageName',
  APP_VERSION: 'appVersion',
  OPT_IN: 'pushNotificationEnabled',
  UNINSTALLED: 'uninstalled'
};

export const AVAILABLE_FILTERS = {
  [FILTER_GROUPS.USER_ATTRIBUTES]: [
    FILTERS.EMAIL,
    FILTERS.GENDER,
    FILTERS.NAME,
    FILTERS.LANGUAGE,
    FILTERS.PHONE
  ],
  [FILTER_GROUPS.LOCATION]: [
    FILTERS.LOCATION_LAT,
    FILTERS.LOCATION_LNG,
    FILTERS.COUNTRY,
    FILTERS.ADDRESS,
    FILTERS.STATE,
    FILTERS.CITY,
    FILTERS.ZIPCODE
  ],
  [FILTER_GROUPS.USER_ACTIVIY_ATTRIBUTES]: [
    FILTERS.ACTIVITY
  ],
  [FILTER_GROUPS.DEVICE_AND_APP]: [
    FILTERS.OS_NUMBER,
    FILTERS.DEVICE_VENDOR,
    FILTERS.DEVICE_MODEL,
    FILTERS.DEVICE_PLATFORM,
    FILTERS.CARRIER,
    FILTERS.CONNECTIVITY_TYPE,
    FILTERS.SDK_VERSION,
    FILTERS.PACKAGE_NAME,
    FILTERS.APP_VERSION,
    FILTERS.OPT_IN
  ]
};

export const OPERATOR_SETS = {
  STRING: [
    OPERATORS.EQUAL,
    OPERATORS.NOT_EQUAL,
    OPERATORS.IN,
    OPERATORS.NOT_IN
  ],
  NUMBER: [
    OPERATORS.EQUAL,
    OPERATORS.NOT_EQUAL,
    OPERATORS.GREATER_THAN,
    OPERATORS.GREATER_OR_EQUAL,
    OPERATORS.LESS_THAN,
    OPERATORS.LESS_OR_EQUAL,
    OPERATORS.IN,
    OPERATORS.NOT_IN
  ],
  DATE: [
    OPERATORS.GREATER_THAN,
    OPERATORS.GREATER_OR_EQUAL,
    OPERATORS.LESS_THAN,
    OPERATORS.LESS_OR_EQUAL
  ],
  BOOLEAN: [
    OPERATORS.EQUAL,
    OPERATORS.NOT_EQUAL
  ]
};

export const FILTER_VALUE_TYPE = {
  [FILTERS.EMAIL]: 'STRING',
  [FILTERS.GENDER]: 'STRING',
  [FILTERS.NAME]: 'STRING',
  [FILTERS.LANGUAGE]: 'STRING',
  [FILTERS.PHONE]: 'STRING',
  [FILTERS.LOCATION_LAT]: 'STRING',
  [FILTERS.LOCATION_LNG]: 'STRING',
  [FILTERS.COUNTRY]: 'STRING',
  [FILTERS.ADDRESS]: 'STRING',
  [FILTERS.STATE]: 'STRING',
  [FILTERS.CITY]: 'STRING',
  [FILTERS.ZIPCODE]: 'STRING',
  [FILTERS.ACTIVITY]: 'DATE',
  [FILTERS.OS_NUMBER]: 'STRING',
  [FILTERS.DEVICE_VENDOR]: 'STRING',
  [FILTERS.DEVICE_MODEL]: 'STRING',
  [FILTERS.DEVICE_PLATFORM]: 'STRING',
  [FILTERS.CARRIER]: 'STRING',
  [FILTERS.CONNECTIVITY_TYPE]: 'STRING',
  [FILTERS.SDK_VERSION]: 'NUMBER',
  [FILTERS.PACKAGE_NAME]: 'STRING',
  [FILTERS.APP_VERSION]: 'NUMBER',
  [FILTERS.OPT_IN]: 'BOOLEAN',
  [FILTERS.UNINSTALLED]: 'BOOLEAN'
};

export default {
  OPERATORS,
  LOGICAL_OPERATORS,
  FILTER_GROUPS,
  FILTERS,
  FILTER_VALUE_TYPE,
  OPERATOR_SETS,
  AVAILABLE_FILTERS
};
